contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mitomine channel"
    url: https://nfcore.slack.com/channels/mitomine
    about: Discussion about the nf-core/mitomine pipeline
